version: '2.1'

services:

  master:
    build:
      context: .
      dockerfile: Dockerfile-master
    ports:
      - "15432:5432"

  standby:
    build:
      context: .
      dockerfile: Dockerfile-standby
    ports:
      - "25432:5432"
    links:
      - master:master
