version: '2.1'

services:

  publisher:
    build:
      context: .
      dockerfile: Dockerfile-publisher
    ports:
      - "15432:5432"

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile-subscriber
    ports:
      - "25432:5432"
